spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  main:
    banner-mode: off

logging:
  level:
    org.springframework.boot.autoconfigure: INFO
    org.springframework.context.annotation: WARN
