server:
  # 必须使用8160,后面的微信登录 wx授权回调域配置的是localhost:8160 使用别的端口将来不能测试
  port: 8888
spring:
  servlet:
    multipart:
      # 一次请求的所有文件表单项文件总大小
      max-request-size: 50MB
      # 单个文件表单项文件大小限制 40MB
      max-file-size: 40MB
  # 应用名称
  application:
    name: system-service
  # 数据库的相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.100.105.236:32768/HousingAgents?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ENC(fsdUus9+xYb5D50foc7lpYfYY7NScxsU755PObg1GeFJr+JMmejCwadkAxK0kRYQ)
    password: ENC(Hj0RcjFmH1rZXMFMcL8zkAGL9tq4Owv5YX4cwtbCs4p3PWRq+9ftrpCF8NYJaKT8)
#    type: com.zaxxer.hikari.HikariDataSource
  # 配置文件的切换配置
  profiles:
    active: dev
  # 设置时间日期格式和时区的设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 39.100.105.236
#    host: ${REMOTE_HOST}
    port: 6379
    password: ENC(oR37xvi2ZDCwwXjWaCw2tcJyEhWbyGJ0jZasFiD5ItbRUb9gti+2yKn5eMOYt7luIeOWTA9lQf0edrdxTz1RiA==)
#    password: ${REMOTE_REDIS_PASSWORD}
mybatis-plus:
  type-aliases-package: com.house.agents.entity
  configuration:
    # 启用sql语句的日志输入功能
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 自定义mapper.xml文件的放置的路径
  mapper-locations: classpath*:/mapper/xml/*.xml
  # 主键id雪花算法生成全局配置
  global-config:
    db-config:
      id-type: assign_id

jasypt:
  encryptor:
    password: ${JASYPT_PASS}
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
#    algorithm: PBEWITHHMACSHA512ANDAES_256
#    algorithm: PBEWithMD5AndDES

aliyun:
  oss:
    schema: https://
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: house-agents
    #accessKeyId: 不安全,不使用这种方式
    #accessKeySecret: 不安全,不使用这种方式
# 线程池的参数
threadPool:
  corePoolSize: 500
  maximumPoolSize: 5000
  keepAliveTime: 60
  workQueueSize: 10000